service:
  name: my-money-manager-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  
functions:
  my-money-manager-api:
    handler: src/server.handler
    events:
      - http:
          method: any
          cors: true
          path: api/{proxy+}
    environment:
      MARKET_DATA_URL: https://sandbox.iexapis.com/stable/{{proxy}}?token={{token}}
      MARKET_DATA_TOKEN: ${env:MARKET_DATA_TOKEN}
