service:
  name: my-money-manager-market-data

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  
functions:
  getMarketData:
    handler: handler.getMarketData
    events:
      - http:
          method: any
          cors: true
          path: getMarketData/{proxy+}
    environment:
      MARKET_DATA_URL: https://sandbox.iexapis.com/stable/{{proxy}}?token={{token}}
      MARKET_DATA_TOKEN: ${env:MARKET_DATA_TOKEN, ssm:apiToken}
